/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author praz
 */
public class Form6 extends javax.swing.JFrame {

    /**
     * Creates new form Form5
     */
    DefaultTableModel model; 
    public Form6() {
        initComponents();
        model=(DefaultTableModel)table.getModel();
        String [] br = {"CSE","ISE","ECE","EEE","AU","AR","NT","ME","MR","MATH"};
        String [] bry = new String[58];
        for(int i=0;i<=57;i++){
            bry[i]=Integer.toString(i+1940);
        }
        String [] brm = new String[12];
        for(int i=0;i<12;i++){
            brm[i]=Integer.toString(i+1);
        }
        String [] brd = new String[31];
        for(int i=0;i<31;i++){
            brd[i]=Integer.toString(i+1);
        }
        combo1.setModel(new javax.swing.DefaultComboBoxModel(br));
        comboy.setModel(new javax.swing.DefaultComboBoxModel(bry));
        combom.setModel(new javax.swing.DefaultComboBoxModel(brm));
        combod.setModel(new javax.swing.DefaultComboBoxModel(brd));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.ButtonGroup();
        upbg = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        M = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        txtaddr = new javax.swing.JTextField();
        txtph = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pswd = new javax.swing.JPasswordField();
        pswd2 = new javax.swing.JPasswordField();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txteid = new javax.swing.JTextField();
        comboy = new javax.swing.JComboBox<>();
        combom = new javax.swing.JComboBox<>();
        combod = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        display = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        panela = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        uptid = new javax.swing.JTextField();
        chckname = new javax.swing.JCheckBox();
        chcksex = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        chckaddr = new javax.swing.JCheckBox();
        chckph = new javax.swing.JCheckBox();
        chckdob = new javax.swing.JCheckBox();
        chckeid = new javax.swing.JCheckBox();
        chckbr = new javax.swing.JCheckBox();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        cy = new javax.swing.JComboBox<>();
        cm = new javax.swing.JComboBox<>();
        cd = new javax.swing.JComboBox<>();
        l8 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        update = new javax.swing.JButton();
        clr = new javax.swing.JButton();
        bck = new javax.swing.JButton();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        l5 = new javax.swing.JLabel();
        t5 = new javax.swing.JPasswordField();
        chckpswd = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        del_tid = new javax.swing.JTextField();
        del = new javax.swing.JButton();
        del_back = new javax.swing.JButton();

        btn.add(M);
        btn.add(F);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.cyan);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("TID");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setText("Phone");

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setText("Branch");

        txttid.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        txttid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttidActionPerformed(evt);
            }
        });

        M.setText("Male");

        F.setText("Female");

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setText("Set Password");

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password");

        pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdActionPerformed(evt);
            }
        });

        add.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton14.png")); // NOI18N
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon("/miniproject/B2.png")); // NOI18N
        clear.setBorderPainted(false);
        clear.setContentAreaFilled(false);
        clear.setFocusPainted(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back1.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        back1.setBorderPainted(false);
        back1.setContentAreaFilled(false);
        back1.setFocusPainted(false);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel10.setText("DOB");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel11.setText("Email ID");

        comboy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back1)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttid, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(M)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(F))
                            .addComponent(txtaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtph, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboy, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(combom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combod, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(clear)
                                .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pswd2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pswd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txttid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(M)
                    .addComponent(F))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pswd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back1)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add", jPanel1);

        jPanel2.setBackground(java.awt.Color.cyan);

        display.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton11.png")); // NOI18N
        display.setBorderPainted(false);
        display.setContentAreaFilled(false);
        display.setFocusPainted(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TID", "Name", "Sex", "Address", "DOB", "Phone", "Email ID", "Branch"
            }
        ));
        table.setVisible(false);
        jScrollPane1.setViewportView(table);
        TableColumnModel colMdl = table.getColumnModel();
        colMdl.getColumn(0).setPreferredWidth(70);
        colMdl.getColumn(1).setPreferredWidth(200);
        colMdl.getColumn(2).setPreferredWidth(50);
        colMdl.getColumn(3).setPreferredWidth(200);
        colMdl.getColumn(4).setPreferredWidth(110);
        colMdl.getColumn(5).setPreferredWidth(120);
        colMdl.getColumn(6).setPreferredWidth(240);
        colMdl.getColumn(7).setPreferredWidth(80);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(display)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(164, 164, 164))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jTabbedPane1.addTab("Display", jPanel2);

        panela.setBackground(java.awt.Color.cyan);

        jLabel12.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel12.setText("Enter the TID of the teacher whose details you want to update");

        uptid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uptidActionPerformed(evt);
            }
        });

        chckname.setText("Name");
        chckname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcknameActionPerformed(evt);
            }
        });

        chcksex.setText("Gender");
        chcksex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcksexActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel13.setText("Choose which details you want to update");

        chckaddr.setText("Address");
        chckaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckaddrActionPerformed(evt);
            }
        });

        chckph.setText("Phone");
        chckph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckphActionPerformed(evt);
            }
        });

        chckdob.setText("DOB");
        chckdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckdobActionPerformed(evt);
            }
        });

        chckeid.setText("Email ID");
        chckeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckeidActionPerformed(evt);
            }
        });

        chckbr.setText("Branch");
        chckbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckbrActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l1.setText("Name");
        l1.setVisible(false);

        t1.setVisible(false);

        l2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l2.setText("Address");
        l2.setVisible(false);

        t2.setVisible(false);

        l3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l3.setText("Email ID");
        l3.setVisible(false);

        t3.setVisible(false);

        l4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l4.setText("Phone");
        l4.setVisible(false);

        t4.setVisible(false);

        l6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l6.setText("Gender");
        l6.setVisible(false);

        l7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l7.setText("DOB");
        l7.setVisible(false);

        cy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997" }));
        cy.setVisible(false);

        cm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cm.setVisible(false);

        cd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cd.setVisible(false);

        l8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l8.setText("Branch");
        l8.setVisible(false);

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ISE", "ECE", "EEE", "AU", "AR", "NT", "ME", "MR" }));
        cb.setVisible(false);

        update.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton10.png")); // NOI18N
        update.setBorderPainted(false);
        update.setContentAreaFilled(false);
        update.setFocusPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        clr.setIcon(new javax.swing.ImageIcon("/miniproject/B2.png")); // NOI18N
        clr.setBorderPainted(false);
        clr.setContentAreaFilled(false);
        clr.setFocusPainted(false);
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });

        bck.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        bck.setBorderPainted(false);
        bck.setContentAreaFilled(false);
        bck.setFocusPainted(false);
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });

        upbg.add(Male);
        Male.setText("M");
        Male.setVisible(false);

        upbg.add(Female);
        Female.setText("F");
        Female.setVisible(false);

        l5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l5.setText("Password");
        l5.setVisible(false);

        t5.setVisible(false);

        chckpswd.setText("Password");
        chckpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckpswdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelaLayout = new javax.swing.GroupLayout(panela);
        panela.setLayout(panelaLayout);
        panelaLayout.setHorizontalGroup(
            panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelaLayout.createSequentialGroup()
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uptid, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelaLayout.createSequentialGroup()
                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelaLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelaLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clr)
                                        .addGap(125, 125, 125)
                                        .addComponent(bck))
                                    .addGroup(panelaLayout.createSequentialGroup()
                                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelaLayout.createSequentialGroup()
                                                .addGap(338, 338, 338)
                                                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelaLayout.createSequentialGroup()
                                                        .addComponent(Male)
                                                        .addGap(144, 144, 144)
                                                        .addComponent(Female))
                                                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelaLayout.createSequentialGroup()
                                        .addGap(18, 659, Short.MAX_VALUE)
                                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panelaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelaLayout.createSequentialGroup()
                                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelaLayout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l3)
                                            .addComponent(l1))
                                        .addGap(53, 53, 53)
                                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelaLayout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chckname)
                                            .addComponent(chckdob))
                                        .addGap(172, 172, 172)
                                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chcksex)
                                            .addComponent(chckeid))
                                        .addGap(180, 180, 180)
                                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chckaddr)
                                            .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(chckbr)
                                                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(l4)
                                                    .addComponent(l2))))))
                                .addGap(130, 130, 130)
                                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chckph)
                                    .addComponent(chckpswd))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19)))
                .addGap(93, 93, 93))
            .addGroup(panelaLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l5)
                    .addGroup(panelaLayout.createSequentialGroup()
                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l8)
                            .addComponent(l7))
                        .addGap(73, 73, 73)
                        .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelaLayout.createSequentialGroup()
                                .addComponent(cy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(l6))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelaLayout.setVerticalGroup(
            panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(uptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(41, 41, 41)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckname)
                    .addComponent(chcksex)
                    .addComponent(chckaddr)
                    .addComponent(chckph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckdob)
                    .addComponent(chckeid)
                    .addComponent(chckbr)
                    .addComponent(chckpswd))
                .addGap(32, 32, 32)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(l2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l5)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l6)
                    .addComponent(Male)
                    .addComponent(Female))
                .addGap(28, 28, 28)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l7)
                    .addComponent(cy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l8)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bck, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update", jPanel3);

        jPanel5.setBackground(java.awt.Color.cyan);

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel9.setText("Enter the TID of the teacher whose details you want to delete");

        del.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton12.png")); // NOI18N
        del.setBorderPainted(false);
        del.setContentAreaFilled(false);
        del.setFocusPainted(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        del_back.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        del_back.setBorderPainted(false);
        del_back.setContentAreaFilled(false);
        del_back.setFocusPainted(false);
        del_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(del)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(del_back)
                .addGap(248, 248, 248))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(del_tid, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(428, 428, 428))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(265, 265, 265))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel9)
                .addGap(88, 88, 88)
                .addComponent(del_tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(del, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(del_back, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(163, 163, 163))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Delete", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Display");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        table.setVisible(true);
        while (model.getRowCount()>0)
          {
             model.removeRow(0);
          }
        Statement stmt = null;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        
        SQL = "SELECT * FROM TEACHER;";
        
        try {
            stmt = conn.createStatement();
	    java.sql.ResultSet rs = stmt.executeQuery("Select * from TEACHER");
            while(rs.next()){
               String tid=rs.getString(1);
               String name=rs.getString(2);
               String gender=rs.getString(3);
               String addr=rs.getString(4);
                              
               java.sql.Date date=rs.getDate(5);
               DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
               String d = df.format(date);
               
               long phone=rs.getLong(6);
               String ph=Long.toString(phone);
               String eid=rs.getString(7);
               String branch=rs.getString(8);
               model.addRow(new Object[]{tid,name,gender,addr,d,ph,eid,branch});
            }
            conn.close();
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
			}
        
        
        
    }//GEN-LAST:event_displayActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void txttidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttidActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_back1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        txttid.setText("");
        txtname.setText("");
        txtaddr.setText("");
        txtph.setText("");
        pswd.setText("");
        pswd2.setText("");
        txteid.setText("");
        combo1.setSelectedIndex(0);
        comboy.setSelectedIndex(0);
        combod.setSelectedIndex(0);
        combom.setSelectedIndex(0);
        M.setSelected(true);
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        
        String txt1=txttid.getText();
        String txt2=txtname.getText();
        String txt4=txtaddr.getText();
        String txt6=txtph.getText();
        String txt7=txteid.getText();
        String txt8=combo1.getSelectedItem().toString();
        
        String txt5y=comboy.getSelectedItem().toString();
        String txt5m=combom.getSelectedItem().toString();
        String txt5d=combod.getSelectedItem().toString();
                
        String txt3;
        String passwd=pswd.getText();
        String passwd2=pswd2.getText();
         
        long lph=Long.parseLong(txt6);
        if(M.isSelected())
            txt3="M";
        else
            txt3="F";
        
        SQL="INSERT INTO TEACHER VALUES('"+txt1+"','"+txt2+"','"+txt3+"','"+txt4+"','"+txt5y+"-"+txt5m+"-"+txt5d+"','"+lph+"','"+txt7+"','"+txt8+"');";
        
            try {
            stmt = conn.createStatement();
	    stmt.executeUpdate(SQL);
	} 
        catch (SQLException sqlEx) {
			JOptionPane.showMessageDialog(null,sqlEx);
	}
            
        if(passwd.compareTo(passwd2)==0){
            SQL="INSERT INTO LOGIN VALUES('"+txt1+"','"+passwd+"');";
         try {
            stmt = conn.createStatement();
	    stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Successfully inserted");
            clearActionPerformed(null);
            conn.close();
	} 
        catch (SQLException sqlEx) {
			JOptionPane.showMessageDialog(null,sqlEx);
	}   
        }
        
    }//GEN-LAST:event_addActionPerformed

    private void del_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_del_backActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
       String dtid=del_tid.getText();
       
       Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        
       SQL="DELETE FROM TEACHER WHERE TID='"+dtid+"';";
        
            try {
            stmt = conn.createStatement();
	    stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Successfully deleted");
            conn.close();
	
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
	}
    }//GEN-LAST:event_delActionPerformed

    private void chckaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckaddrActionPerformed
        l2.setVisible(true);
        t2.setVisible(true);
    }//GEN-LAST:event_chckaddrActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bckActionPerformed

    private void chcksexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcksexActionPerformed
        l6.setVisible(true);
        Male.setVisible(true);
        Female.setVisible(true);
    }//GEN-LAST:event_chcksexActionPerformed

    private void chckdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckdobActionPerformed
        l7.setVisible(true);
        cy.setVisible(true);
        cm.setVisible(true);
        cd.setVisible(true);
    }//GEN-LAST:event_chckdobActionPerformed

    private void chckbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckbrActionPerformed
        l8.setVisible(true);
        cb.setVisible(true);
    }//GEN-LAST:event_chckbrActionPerformed

    private void chcknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcknameActionPerformed
        l1.setVisible(true);
        t1.setVisible(true);
    }//GEN-LAST:event_chcknameActionPerformed

    private void chckeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckeidActionPerformed
        l3.setVisible(true);
        t3.setVisible(true);
    }//GEN-LAST:event_chckeidActionPerformed

    private void chckphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckphActionPerformed
        l4.setVisible(true);
        t4.setVisible(true);
    }//GEN-LAST:event_chckphActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
       uptid.setText("");
       chckname.setSelected(false);
       chckaddr.setSelected(false);
       chckeid.setSelected(false);
       chckbr.setSelected(false);
       chckph.setSelected(false);
       chckpswd.setSelected(false);
       chcksex.setSelected(false);
       chckdob.setSelected(false);
       t1.setText("");
       t2.setText("");
       t3.setText("");
       t4.setText("");
       t5.setText("");
       Male.setSelected(true);
       cb.setSelectedIndex(0);
       cy.setSelectedIndex(0);
       cd.setSelectedIndex(0);
       cm.setSelectedIndex(0);
       l1.setVisible(false);
       l2.setVisible(false);
       l3.setVisible(false);
       l4.setVisible(false);
       l5.setVisible(false);
       l6.setVisible(false);
       l7.setVisible(false);
       l8.setVisible(false);
       t1.setVisible(false);
       t2.setVisible(false);
       t3.setVisible(false);
       t4.setVisible(false);
       t5.setVisible(false);
       Male.setVisible(false);
       Female.setVisible(false);
       cy.setVisible(false);
       cm.setVisible(false);
       cd.setVisible(false);
       cb.setVisible(false);
    }//GEN-LAST:event_clrActionPerformed

    private void chckpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckpswdActionPerformed
        l5.setVisible(true);
        t5.setVisible(true);
    }//GEN-LAST:event_chckpswdActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL=addUpdSQL1();
        String sex;
        //String SQL=addUpdSQL1(chckname.getName())+"'"+t1+"'"+addUpdSQL2(uptid.getText());
        if(chckname.isSelected())
            SQL=SQL+"Name ='"+t1.getText()+"',";
        if(chcksex.isSelected()){
            if(Male.isSelected())
                sex="M";
            else
                sex="F";
            SQL=SQL+"Gender ='"+sex+"',";
        }
        if(chckaddr.isSelected())
            SQL=SQL+"Address ='"+t2.getText()+"',";
        if(chckeid.isSelected())
            SQL=SQL+"Email_ID ='"+t3.getText()+"',";
        if(chckph.isSelected())
            SQL=SQL+"Phone ='"+t4.getText()+"',";
        if(chckdob.isSelected())
            SQL=SQL+"DOB ='"+cy.getSelectedItem()+"-"+cm.getSelectedItem()+"-"+cd.getSelectedItem()+"',";
        if(chckbr.isSelected())
            SQL=SQL+"Branch ='"+cb.getSelectedItem()+"',";
        
        SQL=removeLastChar(SQL);
        
        SQL=SQL+addUpdSQL2(uptid.getText());
        
        try {
            stmt = conn.createStatement();
	    stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Successfully updated");
           
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
	}
        
        if(chckpswd.isSelected()){
            SQL="UPDATE LOGIN SET Password='"+t5.getText()+"' WHERE TID='"+uptid.getText()+"';";
            try {
            stmt = conn.createStatement();
	    stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Password successfully updated");
            conn.close();
	
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
	}
            
        }
        
       uptid.setText("");
       chckname.setSelected(false);
       chckaddr.setSelected(false);
       chckeid.setSelected(false);
       chckbr.setSelected(false);
       chckph.setSelected(false);
       chckpswd.setSelected(false);
       chcksex.setSelected(false);
       chckdob.setSelected(false);
       t1.setText("");
       t2.setText("");
       t3.setText("");
       t4.setText("");
       t5.setText("");
       Male.setSelected(true);
       cb.setSelectedIndex(0);
       cy.setSelectedIndex(0);
       cd.setSelectedIndex(0);
       cm.setSelectedIndex(0);
       
       l1.setVisible(false);
       t1.setVisible(false);
       l2.setVisible(false);
       t2.setVisible(false);
       l3.setVisible(false);
       t3.setVisible(false);
       l4.setVisible(false);
       t4.setVisible(false);
       l5.setVisible(false);
       t5.setVisible(false);
       l6.setVisible(false);
       l7.setVisible(false);
       l8.setVisible(false);
       cb.setVisible(false);
       cd.setVisible(false);
       cy.setVisible(false);
       cm.setVisible(false);
       Male.setVisible(false);
       Female.setVisible(false);
    }//GEN-LAST:event_updateActionPerformed

    private void uptidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uptidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton F;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton M;
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton bck;
    private javax.swing.ButtonGroup btn;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JComboBox<String> cd;
    private javax.swing.JCheckBox chckaddr;
    private javax.swing.JCheckBox chckbr;
    private javax.swing.JCheckBox chckdob;
    private javax.swing.JCheckBox chckeid;
    private javax.swing.JCheckBox chckname;
    private javax.swing.JCheckBox chckph;
    private javax.swing.JCheckBox chckpswd;
    private javax.swing.JCheckBox chcksex;
    private javax.swing.JButton clear;
    private javax.swing.JButton clr;
    private javax.swing.JComboBox<String> cm;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combod;
    private javax.swing.JComboBox<String> combom;
    private javax.swing.JComboBox<String> comboy;
    private javax.swing.JComboBox<String> cy;
    private javax.swing.JButton del;
    private javax.swing.JButton del_back;
    private javax.swing.JTextField del_tid;
    private javax.swing.JButton display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JPanel panela;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JPasswordField pswd2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JPasswordField t5;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txteid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtph;
    private javax.swing.JTextField txttid;
    private javax.swing.ButtonGroup upbg;
    private javax.swing.JButton update;
    private javax.swing.JTextField uptid;
    // End of variables declaration//GEN-END:variables
    private static String addUpdSQL1(){
        
        String UPSQL1="UPDATE TEACHER SET ";
        
        return UPSQL1;
    }
    
    private static String addUpdSQL2(String tid){
        
        String UPSQL2=" WHERE TID='"+tid+"';";
        
        return UPSQL2;
    }
    
    private static String removeLastChar(String str) {
        return str.substring(0, str.length() - 1);
}
     

}
