/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author praz
 */
public class Form11 extends javax.swing.JFrame {

    /**
     * Creates new form Form11
     */
    String TID;
    DefaultTableModel model; 
    public Form11() {
        initComponents();
    }
    
    public Form11(String TID) {
        
        initComponents();
        this.TID=TID;
        model=(DefaultTableModel)table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JRadioButton();
        t3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        csub = new javax.swing.JComboBox<>();
        disp = new javax.swing.JButton();
        chnge = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        t4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.cyan);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("Internals");

        buttonGroup1.add(t1);
        t1.setText("1");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(t2);
        t2.setText("2");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(t3);
        t3.setText("3");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Subject Code");

        csub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        csub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csubActionPerformed(evt);
            }
        });

        disp.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton11.png")); // NOI18N
        disp.setBorderPainted(false);
        disp.setContentAreaFilled(false);
        disp.setFocusPainted(false);
        disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispActionPerformed(evt);
            }
        });

        chnge.setIcon(new javax.swing.ImageIcon("/miniproject/B5.png")); // NOI18N
        chnge.setBorderPainted(false);
        chnge.setContentAreaFilled(false);
        chnge.setFocusPainted(false);
        chnge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngeActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USN", "Student Name", "Marks"
            }
        ));
        table.setVisible(false);
        TableColumnModel colMdl = table.getColumnModel();
        colMdl.getColumn(0).setPreferredWidth(100);
        colMdl.getColumn(1).setPreferredWidth(300);
        colMdl.getColumn(2).setPreferredWidth(100);
        jScrollPane1.setViewportView(table);

        buttonGroup1.add(t4);
        t4.setText("Average");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(disp)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(54, 54, 54)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t4))
                            .addComponent(csub, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chnge)
                        .addGap(86, 86, 86)
                        .addComponent(back)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(t1)
                            .addComponent(t2)
                            .addComponent(t3)
                            .addComponent(t4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(csub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(disp)
                            .addComponent(chnge))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void csubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csubActionPerformed
        
    }//GEN-LAST:event_csubActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();

        String SQL="SELECT SCode FROM TEACHES WHERE TID='"+TID+"';";
        
        csub.removeAllItems();
        
        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs=stmt.executeQuery(SQL);
            while(rs.next()){
                csub.addItem(rs.getString(1));
            }
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();

        String SQL="SELECT SCode FROM TEACHES WHERE TID='"+TID+"';";
        
        csub.removeAllItems();
        
        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs=stmt.executeQuery(SQL);
            while(rs.next()){
                csub.addItem(rs.getString(1));
            }
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();

        String SQL="SELECT SCode FROM TEACHES WHERE TID='"+TID+"';";
        
        csub.removeAllItems();
        
        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs=stmt.executeQuery(SQL);
            while(rs.next()){
                csub.addItem(rs.getString(1));
            }
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
    }//GEN-LAST:event_t3ActionPerformed

    private void dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispActionPerformed
        table.setVisible(true);
        while (model.getRowCount()>0)
          {
             model.removeRow(0);
          }
        Statement stmt = null;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        
        try {
            stmt = conn.createStatement();
            stmt.executeUpdate("CALL AverageM()");
        
           
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
			}
        
        
        
        String scode=csub.getSelectedItem().toString();
        
        if(t1.isSelected())
            SQL = "SELECT M.USN,S.Name,M.IA1_Marks FROM MARKS M,STUDENT S,TEACHES T WHERE T.SCode=M.SCode AND M.CID=T.CID AND M.USN=S.USN AND M.SCode='"+scode+"';";
        else if(t2.isSelected())
            SQL = "SELECT M.USN,S.Name,M.IA2_Marks FROM MARKS M,STUDENT S,TEACHES T WHERE T.SCode=M.SCode AND M.CID=T.CID AND M.USN=S.USN AND M.SCode='"+scode+"';";
        else if(t3.isSelected())
            SQL = "SELECT M.USN,S.Name,M.IA3_Marks FROM MARKS M,STUDENT S,TEACHES T WHERE T.SCode=M.SCode AND M.CID=T.CID AND M.USN=S.USN AND M.SCode='"+scode+"';";
        else
            SQL = "SELECT M.USN,S.Name,M.Final_IA FROM MARKS M,STUDENT S,TEACHES T WHERE T.SCode=M.SCode AND M.CID=T.CID AND M.USN=S.USN AND M.SCode='"+scode+"';";
        
        try {
            stmt = conn.createStatement();
	    java.sql.ResultSet rs = stmt.executeQuery(SQL);
            while(rs.next()){
               String usn=rs.getString(1);
               String name=rs.getString(2);
               String marks=rs.getString(3);
               
               model.addRow(new Object[]{usn,name,marks});
            }
            conn.close();
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
			}
        
        
    }//GEN-LAST:event_dispActionPerformed

    private void chngeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngeActionPerformed
        Statement stmt = null;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        String c="";
        int count=0,i=0;
        String[] a=new String[100];
        String[] usn=new String[100];
        int f=0;
        
        String scode=csub.getSelectedItem().toString();
  
        SQL="SELECT COUNT(M.USN) FROM MARKS M,STUDENT S,TEACHES T WHERE T.SCode=M.SCode AND M.CID=T.CID AND M.USN=S.USN AND M.SCode='"+scode+"';";
        
        
        try {
            stmt = conn.createStatement();
	    java.sql.ResultSet rs = stmt.executeQuery(SQL);
            while(rs.next()){
               
            c=rs.getString(1);
               
            }
            count=Integer.parseInt(c);
           
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
			}
        
        for(i=0;i<count;i++){
            a[i]=(String)table.getModel().getValueAt(i,2);
            usn[i]=(String)table.getModel().getValueAt(i,0);       
            if(a[i]==null)
                a[i]="0";
        }
        
        
        try {
            stmt = conn.createStatement();
	    i=0;
            while(i<=count){
                if(t1.isSelected()){
                    SQL = "UPDATE MARKS SET IA1_Marks='"+a[i]+"' WHERE SCode='"+scode+"' AND USN='"+usn[i]+"';";
                }
                else if(t2.isSelected()){
                    SQL = "UPDATE MARKS SET IA2_Marks='"+a[i]+"' WHERE SCode='"+scode+"' AND USN='"+usn[i]+"';";
                }
                else{
                    SQL = "UPDATE MARKS SET IA3_Marks='"+a[i]+"' WHERE SCode='"+scode+"' AND USN='"+usn[i]+"';";
                }
                
                stmt.executeUpdate(SQL);
                i++;
            }
             JOptionPane.showMessageDialog(null, "Successfully inserted");   
            conn.close();
            
           
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
			}
        
        
    }//GEN-LAST:event_chngeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chnge;
    private javax.swing.JComboBox<String> csub;
    private javax.swing.JButton disp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton t1;
    private javax.swing.JRadioButton t2;
    private javax.swing.JRadioButton t3;
    private javax.swing.JRadioButton t4;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
