/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author praz
 */
public class Form8 extends javax.swing.JFrame {

    /**
     * Creates new form Form5
     */
    DefaultTableModel model;
    public Form8() {
        initComponents();
        model=(DefaultTableModel)table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scode = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        csem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbr = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        disp = new javax.swing.JButton();
        bck = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        disptid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        uptid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cs = new javax.swing.JCheckBox();
        cc = new javax.swing.JCheckBox();
        cb = new javax.swing.JCheckBox();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        text3 = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        text4 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        updtclr = new javax.swing.JButton();
        upbck = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        deltid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        del1 = new javax.swing.JRadioButton();
        del2 = new javax.swing.JRadioButton();
        l1 = new javax.swing.JLabel();
        csub = new javax.swing.JComboBox<>();
        l2 = new javax.swing.JLabel();
        ccid = new javax.swing.JComboBox<>();
        delete = new javax.swing.JButton();
        delclr = new javax.swing.JButton();
        delbck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(84, 110));

        jPanel5.setBackground(java.awt.Color.cyan);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setText("TID");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Subject Code");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel3.setText("Subject Name");

        scode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scodeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel4.setText("Sem");

        csem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel5.setText("Branch");

        cbr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ISE", "ECE", "EEE", "AU", "AR", "NT", "ME", "MR", "MATH" }));

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel6.setText("Class");

        add.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton14.png")); // NOI18N
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon("/miniproject/B2.png")); // NOI18N
        clear.setBorderPainted(false);
        clear.setContentAreaFilled(false);
        clear.setFocusPainted(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(71, 71, 71)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scode, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(86, 86, 86))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(scode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(csem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Add", jPanel1);

        jPanel6.setBackground(java.awt.Color.cyan);

        disp.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton11.png")); // NOI18N
        disp.setBorderPainted(false);
        disp.setContentAreaFilled(false);
        disp.setFocusPainted(false);
        disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispActionPerformed(evt);
            }
        });

        bck.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        bck.setBorderPainted(false);
        bck.setContentAreaFilled(false);
        bck.setFocusPainted(false);
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Subject Name", "Sem", "Branch", "Class"
            }
        ));
        table.setVisible(false);
        TableColumnModel colMdl = table.getColumnModel();
        colMdl.getColumn(0).setPreferredWidth(100);
        colMdl.getColumn(1).setPreferredWidth(200);
        colMdl.getColumn(2).setPreferredWidth(70);
        colMdl.getColumn(3).setPreferredWidth(70);
        jScrollPane1.setViewportView(table);

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel7.setText("TID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(disp)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(disptid, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(bck)
                        .addGap(238, 238, 238))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(disptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(disp)
                    .addComponent(bck))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Display", jPanel2);

        jPanel9.setBackground(java.awt.Color.cyan);

        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel10.setText("TID");

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel11.setText("Update");

        cs.setText("Subject");
        cs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csActionPerformed(evt);
            }
        });

        cc.setText("Class");
        cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccActionPerformed(evt);
            }
        });

        cb.setText("Both");
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbl1.setText("Subject Code");
        lbl1.setVisible(false);

        lbl2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbl2.setText("Change from");
        lbl2.setVisible(false);

        text1.setVisible(false);

        lbl3.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbl3.setText("to");
        lbl3.setVisible(false);

        text2.setVisible(false);

        lbl4.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbl4.setText("Class");
        lbl4.setVisible(false);

        text3.setVisible(false);

        lbl5.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbl5.setText("Change from");
        lbl5.setVisible(false);

        lbl6.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        lbl6.setText("to");
        lbl6.setVisible(false);

        text4.setVisible(false);

        update.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton10.png")); // NOI18N
        update.setBorderPainted(false);
        update.setContentAreaFilled(false);
        update.setFocusPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        updtclr.setIcon(new javax.swing.ImageIcon("/miniproject/B2.png")); // NOI18N
        updtclr.setBorderPainted(false);
        updtclr.setContentAreaFilled(false);
        updtclr.setFocusPainted(false);
        updtclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtclrActionPerformed(evt);
            }
        });

        upbck.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        upbck.setBorderPainted(false);
        upbck.setContentAreaFilled(false);
        upbck.setFocusPainted(false);
        upbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upbckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(204, 204, 204)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uptid, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(cs)
                                        .addGap(51, 51, 51)
                                        .addComponent(cc)
                                        .addGap(36, 36, 36)
                                        .addComponent(cb))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(207, 207, 207))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(update)
                                .addGap(486, 486, 486)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl4)
                                    .addComponent(lbl2)
                                    .addComponent(lbl1)
                                    .addComponent(lbl5))
                                .addGap(496, 496, 496)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl3)
                                    .addComponent(lbl6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGap(522, 522, 522)
                                .addComponent(updtclr)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(upbck)
                        .addGap(71, 71, 71))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(uptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cs)
                    .addComponent(cc)
                    .addComponent(cb))
                .addGap(64, 64, 64)
                .addComponent(lbl1)
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl5)
                            .addComponent(lbl6)
                            .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbl4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updtclr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(upbck, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update", jPanel3);

        jPanel10.setBackground(java.awt.Color.cyan);

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel8.setText("TID");

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel9.setText("Delete By");

        buttonGroup1.add(del1);
        del1.setText("By Subject Code");
        del1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(del2);
        del2.setText("By Class");
        del2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del2ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l1.setText("Subject Code");
        l1.setVisible(false);

        csub.setVisible(false);
        csub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        csub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csubActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        l2.setText("Class");
        l2.setVisible(false);

        ccid.setVisible(false);
        ccid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        delete.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton12.png")); // NOI18N
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setFocusPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        delclr.setIcon(new javax.swing.ImageIcon("/miniproject/B2.png")); // NOI18N
        delclr.setBorderPainted(false);
        delclr.setContentAreaFilled(false);
        delclr.setFocusPainted(false);
        delclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delclrActionPerformed(evt);
            }
        });

        delbck.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        delbck.setBorderPainted(false);
        delbck.setContentAreaFilled(false);
        delbck.setFocusPainted(false);
        delbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(l2)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(delete)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(del1)
                                .addGap(27, 27, 27)
                                .addComponent(del2))
                            .addComponent(deltid, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ccid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(csub, javax.swing.GroupLayout.Alignment.LEADING, 0, 188, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(delclr)
                        .addGap(170, 170, 170)
                        .addComponent(delbck)
                        .addGap(135, 135, 135))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delbck))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(deltid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(del1)
                            .addComponent(del2))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l1)
                            .addComponent(csub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l2)
                            .addComponent(ccid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delclr)
                            .addComponent(delete))))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Delete", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scodeActionPerformed
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();

        String SQL="SELECT SName FROM SUBJECT WHERE SCode='"+scode.getText()+"';";

        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs=stmt.executeQuery(SQL);
            while(rs.next()){
                sname.setText(rs.getString(1));
            }
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
    }//GEN-LAST:event_scodeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String txt1=tid.getText();
        String txt2=scode.getText();
        String txt3;
        int txt4=Integer.parseInt(csem.getSelectedItem().toString());
        String txt5=cbr.getSelectedItem().toString();
        String txt6=cid.getText();

        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";

        SQL="INSERT INTO TEACHES VALUES('"+txt1+"','"+txt2+"','"+txt6+"');";

        try {
            stmt = conn.createStatement();
            stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Successfully added");
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
        
        clearActionPerformed(null);
    }//GEN-LAST:event_addActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        tid.setText("");
        scode.setText("");
        sname.setText("");
        cid.setText("");
        cbr.setSelectedIndex(0);
        csem.setSelectedIndex(0);
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bckActionPerformed

    private void dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispActionPerformed
        table.setVisible(true);
        while (model.getRowCount()>0)
          {
             model.removeRow(0);
          }
        String tid=disptid.getText();
        
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();

        String SQL="SELECT S.SCode,S.SName,S.Sem,S.Branch,T.CID FROM SUBJECT S,TEACHES T WHERE S.SCode=T.SCode AND T.TID='"+tid+"';";

        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs=stmt.executeQuery(SQL);
            while(rs.next()){
                String scode=rs.getString(1);
                String sname=rs.getString(2);
                String sem=rs.getString(3);
                String branch=rs.getString(4);
                String cid=rs.getString(5);
                model.addRow(new Object[]{scode,sname,sem,branch,cid});
            }
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
    }//GEN-LAST:event_dispActionPerformed

    private void delbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbckActionPerformed
        setVisible(false);
    }//GEN-LAST:event_delbckActionPerformed

    private void delclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delclrActionPerformed
        deltid.setText("");
        del1.setSelected(true);
        csub.setSelectedIndex(0);
        csub.removeAllItems();
        csub.addItem("All");
        ccid.setSelectedIndex(0);
        ccid.removeAllItems();
        ccid.addItem("All");   
        l1.setVisible(false);
        csub.setVisible(false);        
        l2.setVisible(false);
        ccid.setVisible(false);
        
    }//GEN-LAST:event_delclrActionPerformed

    private void del1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del1ActionPerformed
        l1.setVisible(true);
        csub.setVisible(true);
        
        l2.setVisible(false);
        ccid.setVisible(false);
        
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();

        String SQL="SELECT SCode FROM TEACHES WHERE TID='"+deltid.getText()+"';";
        
        csub.removeAllItems();
        csub.addItem("All");
        ccid.removeAllItems();
        ccid.addItem("All");
        
        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs=stmt.executeQuery(SQL);
            while(rs.next()){
                csub.addItem(rs.getString(1));
            }
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
    }//GEN-LAST:event_del1ActionPerformed

    private void del2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del2ActionPerformed
        l1.setVisible(false);
        csub.setVisible(false);
        
        l2.setVisible(true);
        ccid.setVisible(true);
        
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();

        String SQL="SELECT CID FROM TEACHES WHERE TID='"+deltid.getText()+"';";

        csub.removeAllItems();
        csub.addItem("All");
        ccid.removeAllItems();
        ccid.addItem("All");
        
        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs=stmt.executeQuery(SQL);
            while(rs.next()){
                ccid.addItem(rs.getString(1));
            }
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }
    }//GEN-LAST:event_del2ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       String dtid=deltid.getText();
       
       Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        String sub=csub.getSelectedItem().toString();
        String cid=ccid.getSelectedItem().toString();
        
        if(csub.getItemCount()==1){
            JOptionPane.showMessageDialog(null, "Nothing to delete");
            csub.setSelectedIndex(0);
            csub.removeAllItems();
            csub.addItem("All");
            ccid.setSelectedIndex(0);
            ccid.removeAllItems();
            ccid.addItem("All");   
        
        }
        
        else if(ccid.getItemCount()==1){
            JOptionPane.showMessageDialog(null, "Nothing to delete");
            csub.setSelectedIndex(0);
            csub.removeAllItems();
            csub.addItem("All");
            ccid.setSelectedIndex(0);
            ccid.removeAllItems();
            ccid.addItem("All");   
        
        }
        
        else if(del1.isSelected()){
            if(sub.equals("All")){
                SQL="DELETE FROM TEACHES WHERE SCode IN(SELECT SCode FROM TEACHES WHERE TID='"+dtid+"');";
            }
            else{
                SQL="DELETE FROM TEACHES WHERE TID='"+dtid+"' AND SCode='"+sub+"';";
            }
        }
        else{
            if(cid.equals("All")){
                SQL="DELETE FROM TEACHES WHERE CID IN(SELECT CID FROM TEACHES WHERE TID='"+dtid+"');";
            }
            else{
                SQL="DELETE FROM TEACHES WHERE TID='"+dtid+"' AND CID='"+cid+"';";
            }
        }
       
        
            try {
            stmt = conn.createStatement();
	    stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Successfully deleted");
            conn.close();
	
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
	}
            
            delclrActionPerformed(null);
    }//GEN-LAST:event_deleteActionPerformed

    private void upbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upbckActionPerformed
        setVisible(false);
    }//GEN-LAST:event_upbckActionPerformed

    private void updtclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtclrActionPerformed
        lbl1.setVisible(false);
        lbl2.setVisible(false);
        lbl3.setVisible(false);
        lbl4.setVisible(false);
        lbl5.setVisible(false);
        lbl6.setVisible(false);
        text1.setText("");
        text1.setVisible(false);
        text2.setText("");
        text2.setVisible(false);
        text3.setText("");
        text3.setVisible(false);
        text4.setText("");
        text4.setVisible(false);
        uptid.setText("");
        cs.setSelected(false);
        cc.setSelected(false);
        cb.setSelected(false);
    }//GEN-LAST:event_updtclrActionPerformed

    private void csActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csActionPerformed
        lbl1.setVisible(true);
        lbl2.setVisible(true);
        lbl3.setVisible(true);
        text1.setText("");
        text1.setVisible(true);
        text2.setText("");
        text2.setVisible(true);
    }//GEN-LAST:event_csActionPerformed

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        lbl4.setVisible(true);
        lbl5.setVisible(true);
        lbl6.setVisible(true);
        text3.setText("");
        text3.setVisible(true);
        text4.setText("");
        text4.setVisible(true);
    }//GEN-LAST:event_ccActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        lbl1.setVisible(true);
        lbl2.setVisible(true);
        lbl3.setVisible(true);
        text1.setText("");
        text1.setVisible(true);
        text2.setText("");
        text2.setVisible(true);
        lbl4.setVisible(true);
        lbl5.setVisible(true);
        lbl6.setVisible(true);
        text3.setText("");
        text3.setVisible(true);
        text4.setText("");
        text4.setVisible(true);
    }//GEN-LAST:event_cbActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        Statement stmt;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        String tid=uptid.getText();
        String txt1=text1.getText();
        String txt2=text2.getText();
        String txt3=text3.getText();
        String txt4=text4.getText();
        
        if(cb.isSelected())
            SQL="UPDATE TEACHES SET SCode='"+txt2+"',CID='"+txt4+"' WHERE TID='"+tid+"' AND SCode='"+txt1+"' AND CID='"+txt3+"';";
        else if(cs.isSelected())
            SQL="UPDATE TEACHES SET SCode='"+txt2+"' WHERE TID='"+tid+"' AND SCode='"+txt1+"';";
        else
            SQL="UPDATE TEACHES SET CID='"+txt4+"' WHERE TID='"+tid+"' AND CID='"+txt3+"';";
        
        try {
            stmt = conn.createStatement();
	    stmt.executeUpdate(SQL);
            JOptionPane.showMessageDialog(null, "Successfully updated");
            conn.close();
           
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
	}    
        
        updtclrActionPerformed(null);
    }//GEN-LAST:event_updateActionPerformed

    private void csubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csubActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton bck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb;
    private javax.swing.JComboBox<String> cbr;
    private javax.swing.JCheckBox cc;
    private javax.swing.JComboBox<String> ccid;
    private javax.swing.JTextField cid;
    private javax.swing.JButton clear;
    private javax.swing.JCheckBox cs;
    private javax.swing.JComboBox<String> csem;
    private javax.swing.JComboBox<String> csub;
    private javax.swing.JRadioButton del1;
    private javax.swing.JRadioButton del2;
    private javax.swing.JButton delbck;
    private javax.swing.JButton delclr;
    private javax.swing.JButton delete;
    private javax.swing.JTextField deltid;
    private javax.swing.JButton disp;
    private javax.swing.JTextField disptid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JTextField scode;
    private javax.swing.JTextField sname;
    private javax.swing.JTable table;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField tid;
    private javax.swing.JButton upbck;
    private javax.swing.JButton update;
    private javax.swing.JButton updtclr;
    private javax.swing.JTextField uptid;
    // End of variables declaration//GEN-END:variables
}
