/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author praz
 */
public class Form12 extends javax.swing.JFrame {

    /**
     * Creates new form Form12
     */
    String TID;
     DefaultTableModel model; 
    public Form12() {
        initComponents();
    }
    
    public Form12(String TID) {
        initComponents();
        this.TID=TID;
        model=(DefaultTableModel)table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        disp = new javax.swing.JButton();
        chnge = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        scode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.cyan);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Subject Code");

        disp.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton11.png")); // NOI18N
        disp.setBorderPainted(false);
        disp.setContentAreaFilled(false);
        disp.setFocusPainted(false);
        disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispActionPerformed(evt);
            }
        });

        chnge.setIcon(new javax.swing.ImageIcon("/miniproject/B5.png")); // NOI18N
        chnge.setBorderPainted(false);
        chnge.setContentAreaFilled(false);
        chnge.setFocusPainted(false);
        chnge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngeActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon("/miniproject/MiniButton4.png")); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setFocusPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USN", "Student Name", "Attended Classes", "Total Classes", "Percentage"
            }
        ));
        table.setVisible(false);
        TableColumnModel colMdl = table.getColumnModel();
        colMdl.getColumn(0).setPreferredWidth(100);
        colMdl.getColumn(1).setPreferredWidth(300);
        colMdl.getColumn(2).setPreferredWidth(100);
        colMdl.getColumn(3).setPreferredWidth(100);
        colMdl.getColumn(4).setPreferredWidth(100);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(disp)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(chnge)
                        .addGap(86, 86, 86)
                        .addComponent(back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(scode, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(scode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(disp)
                            .addComponent(chnge))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispActionPerformed
        table.setVisible(true);
        while (model.getRowCount()>0)
          {
             model.removeRow(0);
          }
        Statement stmt = null;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        
        try {
            stmt = conn.createStatement();
            stmt.executeUpdate("CALL PercA()");
           
	} 
        catch (SQLException sqlEx) {
			System.out.println(sqlEx);
			}
        
        String scd=scode.getText();

        SQL = "SELECT A.USN,S.Name,A.Attd_Class,A.Total_Class,A.Percentage FROM ATTENDANCE A,STUDENT S,TEACHES T WHERE T.SCode=A.SCode AND A.CID=T.CID AND A.USN=S.USN AND A.SCode='"+scd+"';";
        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(SQL);
            while(rs.next()){
                String usn=rs.getString(1);
                String name=rs.getString(2);
                String attd=rs.getString(3);
                String total=rs.getString(4);
                String perc=rs.getString(5);

                model.addRow(new Object[]{usn,name,attd,total,perc});
            }
            conn.close();
        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }

    }//GEN-LAST:event_dispActionPerformed

    private void chngeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngeActionPerformed
        Statement stmt = null;
        Connection conn;
        conn = Conn12.getConnection();
        String SQL="";
        String c="";
        int count=0,i=0;
        String[] a1=new String[100];
        String[] a2=new String[100];
        String[] usn=new String[100];

        String scd=scode.getText();
        SQL="SELECT COUNT(A.USN) FROM ATTENDANCE A,STUDENT S,TEACHES T WHERE T.SCode=A.SCode AND A.CID=T.CID AND A.USN=S.USN AND A.SCode='"+scd+"';";

        try {
            stmt = conn.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(SQL);
            while(rs.next()){
                c=rs.getString(1);
            }
            count=Integer.parseInt(c);

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }

        for(i=0;i<count;i++){
            
            a1[i]=(String)table.getModel().getValueAt(i,2);
            a2[i]=(String)table.getModel().getValueAt(i,3);  
            usn[i]=(String)table.getModel().getValueAt(i,0);
            if(a1[i]==null)
                a1[i]="0";
            if(a2[i]==null)
                a2[i]="0";
            
        }

        try {
            stmt = conn.createStatement();
            i=0;
            while(i<=count){
               
               SQL="UPDATE ATTENDANCE SET Attd_Class='"+a1[i]+"',Total_Class='"+a2[i]+"' WHERE SCode='"+scd+"' AND USN='"+usn[i]+"';";
               stmt.executeUpdate(SQL);
               i++;
            }
            
            
            JOptionPane.showMessageDialog(null, "Successfully inserted");
            conn.close();

        }
        catch (SQLException sqlEx) {
            System.out.println(sqlEx);
        }

    }//GEN-LAST:event_chngeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton chnge;
    private javax.swing.JButton disp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField scode;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
