/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author praz
 */
public class Form3 extends javax.swing.JFrame {
    String USN="";
    /**
     * Creates new form Form3
     */
    public Form3() {
        initComponents();
        
    }
    
    public Form3(String USN) {
        initComponents();
        this.USN=USN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cpanel = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t19 = new javax.swing.JTextField();
        t20 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.black);
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.orange));

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setIcon(new javax.swing.ImageIcon("/miniproject/Camera.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setIcon(new javax.swing.ImageIcon("/miniproject/left-arrow-clipart-png-15.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.white);
        jButton3.setIcon(new javax.swing.ImageIcon("/miniproject/clear-clear-icon-95335.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        cpanel.setSize(2000, 2000);
        cpanel.setBackground(new java.awt.Color(253, 253, 100));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        //t1.setVisible(false);

        //t2.setVisible(false);

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        //t3.setVisible(false);

        //t4.setVisible(false);

        //t5.setVisible(false);
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        //t6.setVisible(false);

        //t7.setVisible(false);
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        //t8.setVisible(false);

        //t9.setVisible(false);
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });

        //t10.setVisible(false);

        //t11.setVisible(false);
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });

        //t12.setVisible(false);

        //t13.setVisible(false);
        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });

        //t14.setVisible(false);

        //t15.setVisible(false);
        t15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t15ActionPerformed(evt);
            }
        });

        //t16.setVisible(false);

        //t17.setVisible(false);
        t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t17ActionPerformed(evt);
            }
        });

        //t18.setVisible(false);

        //t19.setVisible(false);
        t19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t19ActionPerformed(evt);
            }
        });

        t20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t20ActionPerformed(evt);
            }
        });
        //t20.setVisible(false);

        javax.swing.GroupLayout cpanelLayout = new javax.swing.GroupLayout(cpanel);
        cpanel.setLayout(cpanelLayout);
        cpanelLayout.setHorizontalGroup(
            cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cpanelLayout.createSequentialGroup()
                        .addGroup(cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t18, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(t16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t17, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(t15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(cpanelLayout.createSequentialGroup()
                        .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        cpanelLayout.setVerticalGroup(
            cpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(cpanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Screenshot.take_shot();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        t9.setText("");
        t10.setText("");
        t11.setText("");
        t12.setText("");
        t13.setText("");
        t14.setText("");
        t15.setText("");
        t16.setText("");
        t17.setText("");
        t18.setText("");
        t19.setText("");
        t20.setText("");
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        if(t2.getText().compareTo("Subject code of the subject for marks")==0){
            t3.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t3.getText(),USN);
                t4.setText(ans);
            }
        }
    });
        }
        
        else if(t2.getText().compareTo("Subject code of the subject for attendance")==0){
            t3.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t3.getText(),USN);
                t4.setText(ans);
            }
        }
    });
        }
        
        else if(t2.getText().compareTo("Subject code of the subject for exams")==0){
            t3.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t3.getText(),USN);
                t4.setText(ans);
            }
        }
    });
        }
        
        else if(t2.getText().compareTo("Subject code of the subject for the teacher")==0){
            t3.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t3.getText(),USN);
                t4.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t3.getText(),USN);
        t4.setText(ans);
        }
        
    }//GEN-LAST:event_t3ActionPerformed

    private void t20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t20ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        String ans=Chatbot.start_chat(t1.getText(),USN);
        t2.setText(ans);
        
        
    }//GEN-LAST:event_t1ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        if(t4.getText().compareTo("Subject code of the subject for marks")==0){
            t5.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t5.getText(),USN);
                t6.setText(ans);
            }
        }
    });
        }
        
        else if(t4.getText().compareTo("Subject code of the subject for attendance")==0){
            t5.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t5.getText(),USN);
                t6.setText(ans);
            }
        }
    });
        }
        
        else if(t4.getText().compareTo("Subject code of the subject for exams")==0){
            t5.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t5.getText(),USN);
                t6.setText(ans);
            }
        }
    });
        }
        
        else if(t4.getText().compareTo("Subject code of the subject for the teacher")==0){
            t5.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t5.getText(),USN);
                t6.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t5.getText(),USN);
        t6.setText(ans);
        }
    }//GEN-LAST:event_t5ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        if(t6.getText().compareTo("Subject code of the subject for marks")==0){
            t7.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t7.getText(),USN);
                t8.setText(ans);
            }
        }
    });
        }
        
        else if(t6.getText().compareTo("Subject code of the subject for attendance")==0){
            t7.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t7.getText(),USN);
                t8.setText(ans);
            }
        }
    });
        }
        
        else if(t6.getText().compareTo("Subject code of the subject for exams")==0){
            t7.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t7.getText(),USN);
                t8.setText(ans);
            }
        }
    });
        }
        
        else if(t6.getText().compareTo("Subject code of the subject for the teacher")==0){
            t7.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t7.getText(),USN);
                t8.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t7.getText(),USN);
        t8.setText(ans);
        }
        
    }//GEN-LAST:event_t7ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        if(t8.getText().compareTo("Subject code of the subject for marks")==0){
            t9.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t9.getText(),USN);
                t10.setText(ans);
            }
        }
    });
        }
        
        else if(t8.getText().compareTo("Subject code of the subject for attendance")==0){
            t9.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t9.getText(),USN);
                t10.setText(ans);
            }
        }
    });
        }
        
        else if(t8.getText().compareTo("Subject code of the subject for exams")==0){
            t9.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t9.getText(),USN);
                t10.setText(ans);
            }
        }
    });
        }
        
        else if(t8.getText().compareTo("Subject code of the subject for the teacher")==0){
            t9.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t9.getText(),USN);
                t10.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t9.getText(),USN);
        t10.setText(ans);
        }
        
    }//GEN-LAST:event_t9ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        if(t10.getText().compareTo("Subject code of the subject for marks")==0){
            t11.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t11.getText(),USN);
                t12.setText(ans);
            }
        }
    });
        }
        
        else if(t10.getText().compareTo("Subject code of the subject for attendance")==0){
            t11.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t11.getText(),USN);
                t12.setText(ans);
            }
        }
    });
        }
        
        else if(t10.getText().compareTo("Subject code of the subject for exams")==0){
            t11.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t11.getText(),USN);
                t12.setText(ans);
            }
        }
    });
        }
        
        else if(t10.getText().compareTo("Subject code of the subject for the teacher")==0){
            t11.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t11.getText(),USN);
                t12.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t11.getText(),USN);
        t12.setText(ans);
        }
        
    }//GEN-LAST:event_t11ActionPerformed

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t13ActionPerformed
        if(t12.getText().compareTo("Subject code of the subject for marks")==0){
            t13.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t13.getText(),USN);
                t14.setText(ans);
            }
        }
    });
        }
        
        else if(t12.getText().compareTo("Subject code of the subject for attendance")==0){
            t13.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t13.getText(),USN);
                t14.setText(ans);
            }
        }
    });
        }
        
        else if(t12.getText().compareTo("Subject code of the subject for exams")==0){
            t13.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t13.getText(),USN);
                t14.setText(ans);
            }
        }
    });
        }
        
        else if(t12.getText().compareTo("Subject code of the subject for the teacher")==0){
            t13.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t13.getText(),USN);
                t14.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t13.getText(),USN);
        t14.setText(ans);
        }
        
    }//GEN-LAST:event_t13ActionPerformed

    private void t15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t15ActionPerformed
       if(t14.getText().compareTo("Subject code of the subject for marks")==0){
            t15.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t15.getText(),USN);
                t16.setText(ans);
            }
        }
    });
        }
        
        else if(t14.getText().compareTo("Subject code of the subject for attendance")==0){
            t15.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t15.getText(),USN);
                t16.setText(ans);
            }
        }
    });
        }
        
        else if(t14.getText().compareTo("Subject code of the subject for exams")==0){
            t15.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t15.getText(),USN);
                t16.setText(ans);
            }
        }
    });
        }
        
        else if(t14.getText().compareTo("Subject code of the subject for the teacher")==0){
            t15.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t15.getText(),USN);
                t16.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t15.getText(),USN);
        t16.setText(ans);
        }
         
    }//GEN-LAST:event_t15ActionPerformed

    private void t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t17ActionPerformed
       if(t16.getText().compareTo("Subject code of the subject for marks")==0){
            t17.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t17.getText(),USN);
                t18.setText(ans);
            }
        }
    });
        }
        
        else if(t16.getText().compareTo("Subject code of the subject for attendance")==0){
            t17.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t17.getText(),USN);
                t18.setText(ans);
            }
        }
    });
        }
        
        else if(t16.getText().compareTo("Subject code of the subject for exams")==0){
            t17.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t17.getText(),USN);
                t18.setText(ans);
            }
        }
    });
        }
        
        else if(t16.getText().compareTo("Subject code of the subject for the teacher")==0){
            t17.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t17.getText(),USN);
                t18.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t17.getText(),USN);
        t18.setText(ans);
        }
        
    }//GEN-LAST:event_t17ActionPerformed

    private void t19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t19ActionPerformed
       if(t18.getText().compareTo("Subject code of the subject for marks")==0){
            t19.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.marks(t19.getText(),USN);
                t20.setText(ans);
            }
        }
    });
        }
        
        else if(t18.getText().compareTo("Subject code of the subject for attendance")==0){
            t19.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.attends(t19.getText(),USN);
                t20.setText(ans);
            }
        }
    });
        }
        
        else if(t18.getText().compareTo("Subject code of the subject for exams")==0){
            t19.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.exams(t19.getText(),USN);
                t20.setText(ans);
            }
        }
    });
        }
        
        else if(t18.getText().compareTo("Subject code of the subject for the teacher")==0){
            t19.addKeyListener(new KeyAdapter() {
        public void keyPressed(KeyEvent evt)
        {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                String ans=Functions.teach(t19.getText(),USN);
                t20.setText(ans);
            }
        }
    });
        }
        
        else{
        
        String ans=Chatbot.start_chat(t19.getText(),USN);
        t20.setText(ans);
        }
        
    }//GEN-LAST:event_t19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
       
  
    
}
